#!/bin/bash

export REQUEST_METHOD="GET"
export QUERY_STRING="addresses=0x..."

# ./balance

export QUERY_STRING="addresses=0x...,0x..."

# ./balance

export REQUEST_METHOD="POST"

#./balance <<< '["0x43133b094c9d78BBB7030f9bABF48C056905d529"]'

./balance <<EOI
["0x...",
 "0x...",
 "0x...",
 "0x..."]
EOI
