#!/home/skull/nodejs/bin/node

// A CGI program that scans an Ethereum Stealth Pubkey registry for all
// events that have occurred since a given timestamp

const fs = require( 'fs' )
const wss = require( 'ws' )
const ecjson = require( './ecjsonrpc.js' )

// const WSURL = 'ws://10.0.0.113:8888'
const WSURL = 'ws://70.66.248.196:8888'

const privkeyhex =
  "ed799fbaa3ee5ec823155c744523c4ac1cc1ac5bb1b8c85d5f884cb1c07e5138"

var mylog = fs.createWriteStream( './epkscan.txt', {flags:'a'} )

function timestamp() {
  let now = new Date()
  let mon = now.getUTCMonth() + 1
  if (mon < 10) mon = '0' + mon
  let day = now.getUTCDate()
  if (day < 10) day = '0' + day
  let hr = now.getUTCHours()
  if (hr < 10) hr = '0' + hr
  let min = now.getUTCMinutes()
  if (min < 10) min = '0' + min
  return '' + now.getUTCFullYear() + mon + day + ':' + hr + min
}

function queryEvents( sinceTimestamp ) {
  let ws = new wss.WebSocket( WSURL )

  ws.on('error', mylog.write )
  ws.on('message', msgdata => {
    let obj

    try {
      obj = JSON.parse( msgdata.toString() )

      // the hello comes back as red text
      if (obj.method === "hello") {
        let gwpubkeyhex = obj.params[0]

        let scanreq = JSON.parse( JSON.stringify(ecjson.REQUEST) )
        scanreq.method = "eth.epkscan"
        scanreq.params = [ sinceTimestamp ]
        scanreq.id = process.pid

        let blackreq = ecjson.redToBlack( privkeyhex, gwpubkeyhex, scanreq )

        ws.send( JSON.stringify(blackreq) )
      }
      // an error could come back as red text
      else if (obj.error) {
        throw JSON.stringify( obj.error )
      }
      else if (obj.msghex) {
        let redobj = ecjson.blackToRed( privkeyhex, obj )

        if (redobj.error)
          throw JSON.stringify(redobj.error)

        let rspobj = { result: redobj.result }
        console.log( "Content-Type: application/json\r\n\r\n" )
        console.log( JSON.stringify(rspobj) )
        ws.close()
      }
      else {
        throw 'unrecognized response: ' + msgdata.toString()
      }
    }
    catch (ex) {
      mylog.write( ex.toString() + '\n' )
      let errobj = { error: { code: 500, message: ex.toString() } }
      console.log( "Content-Type: application/json\r\n\r\n" )
      console.log( JSON.stringify(errobj) )
      ws.close()
    }
  } )
}

function handleGet() {
  let param = process.env.QUERY_STRING.split('=')
  if (!param || param.length != 2 || param[0] !== 'starttimestamp')
    throw 'GET: QUERY_STRING missing starttimestamp parameter'
  queryEvents( parseInt(param[1]) )
}

function handlePost() {
  let contentlength = process.env.CONTENT_LENGTH

  process.stdin.on('data', data => {
    let body = JSON.parse( data.toString() )
    if (!body || !body.starttimestamp || body.starttimestamp.length == 0)
      throw 'POST: expected starttimestamp value'

    queryEvents( body.starttimestamp )
  });
}

// =====
//  MAIN
// =====

try {
  mylog.write( timestamp() + ' ' + process.env.REMOTE_ADDR + '\n' )

  if (process.env.REQUEST_METHOD === 'GET') {
    handleGet()
  }
  else
  if (process.env.REQUEST_METHOD === 'POST') {
    handlePost()
  }
  else
    throw "unrecognized REQUEST_METHOD: " + process.env.REQUEST_METHOD
}
catch( ex ) {
  mylog.write( ex.toString() + '\n' )
  let errobj = { error: { code:500, message:ex.toString() } }
  console.log( "Content-Type: application/json\r\n\r\n" )
  console.log( JSON.stringify(errobj) )
}
